# type: ignore
"""add download_task table

Revision ID: f4fb4d42a827
Revises: 27b628a63d4e
Create Date: 2026-02-14 15:21:16.594635+00:00

"""

from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import (
    EncryptedString,
    EncryptedText,
    GUID,
    ORA_JSONB,
    DateTimeUTC,
)
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import sqlite

if TYPE_CHECKING:
    pass

__all__ = [
    "downgrade",
    "upgrade",
    "schema_upgrades",
    "schema_downgrades",
    "data_upgrades",
    "data_downgrades",
]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = "f4fb4d42a827"
down_revision = "27b628a63d4e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "download_task",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("repo_id", sa.String(), nullable=False),
        sa.Column("profile", sa.String(), nullable=False),
        sa.Column("revision", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("model_id", sa.GUID(length=16), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_download_task")),
    )
    op.create_index("ix_download_task_status", "download_task", ["status"])
    op.create_index("ix_download_task_profile", "download_task", ["profile"])
    op.create_index(
        "ix_download_task_profile_status", "download_task", ["profile", "status"]
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pipeline", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("cache_dir", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("job_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("ntotal", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("nsuccess", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("nfail", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("scheduler", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "provider",
                sa.Enum("Docker", "Apptainer", name="containerprovider"),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("mount", sa.String(), nullable=True))
        batch_op.drop_column("errored")
        batch_op.drop_column("output_dir")
        batch_op.drop_column("input_ext")
        batch_op.drop_column("pid")
        batch_op.drop_column("task")
        batch_op.drop_column("output_ext")
        batch_op.drop_column("params")
        batch_op.drop_column("input_dir")
        batch_op.drop_column("staged")
        batch_op.drop_column("resources")
        batch_op.drop_column("finished")
        batch_op.drop_column("revision")

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("revision", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("finished", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("resources", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("staged", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("input_dir", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("params", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("output_ext", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("task", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("pid", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("input_ext", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("output_dir", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("errored", sa.VARCHAR(), nullable=True))
        batch_op.drop_column("mount")
        batch_op.drop_column("provider")
        batch_op.drop_column("scheduler")
        batch_op.drop_column("nfail")
        batch_op.drop_column("nsuccess")
        batch_op.drop_column("ntotal")
        batch_op.drop_column("job_id")
        batch_op.drop_column("cache_dir")
        batch_op.drop_column("pipeline")

    op.drop_index("ix_download_task_profile_status", "download_task")
    op.drop_index("ix_download_task_profile", "download_task")
    op.drop_index("ix_download_task_status", "download_task")
    op.drop_table("download_task")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
